version: '3.5'
services:
  postgres:
    image: 'postgres:12.3'
    container_name: ${PROJECT_NAME}-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    networks:
      - django-app
    restart: always

volumes:
  postgres_data: {}

networks:
  django-app:
    driver: bridge
